name: code-cov-ubuntu-latest

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test python API
    steps:
    - uses: actions/checkout@v1
    - name: Install requirements
      run: |
        pip install -r requirements.txt
        pip install pytest-cov
    - name: Run tests and collect coverage
      working-directory: ./datalib
      run: pytest --cov . --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}